name: chessmatey
description: A chess tournament management program.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  yaru: ^1.1.0
  yaru_widgets: ^3.2.2
  handy_window: ^0.3.1
  freezed_annotation: ^2.4.1
  fast_immutable_collections: ^9.1.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true